### PR TITLE
Implemented call rewrite support for ARM

### PR DESCRIPTION
**Pull request by yifanlu**
This supports something like. 
```
func:
bl otherfunc
/* do stuff */
bx lr
```

### CODE REVIEW

**Comment by comex** [comment]
It shouldn't be necessary to save LR, but I'll add the other part.  Dunno how I managed to miss this.  Thanks.

**Comment by yifanlu** [comment]
> It shouldn't be necessary to save LR

Explain? In my example above, the BL is followed by other instructions. If you don't save LR (and then set it accordingly), how do you execute the remaining saved instructions?

**Comment by comex** [comment]
We have to set LR before jumping (I just pushed something which does that with BLX instead), but the existing value of LR before the BLX doesn't have to be saved/restored.  After all, the original code clobbers it.

**Comment by yifanlu** [comment]
Maybe I'm misunderstanding this. So my code => transformed intro would set LR. If the transformed code clobbers LR, then how do we get back to the caller (my code)?

**Comment by comex** [comment]
The code being transformed is the beginning of a function; if it makes a call, it should save LR itself first.  Otherwise it couldn't get back if you called it without transforming it.

**Pull request closed without merging**
